### ISSUE TITLE
The night as bright as day in the latest version.

### ISSUE THREAD

**Issue by HELLORPG** [CubeIR/Vanilla-RTX#10]
Hi, I have the Vanilla-RTX in version 1.7.7 and MC bedrock in version v1.19.40.
I find that if I turn on RTX, the night will be as bright as day. Just like the moon is another sun.
Do you know how to fix this?

Thanks a lot.

**Comment by HELLORPG** [comment]
Here is a ScreenShot at night, just like at noon.
![screen_shot](https://user-images.githubusercontent.com/41836383/198188222-6f233879-b5c4-4b51-ae73-0ee3c1131793.jpg)

**Comment by CubeIR** [comment]
This should get solved on its own with next Minecraft update.
https://bugs.mojang.com/browse/MCPE-162445

**Comment by ABUCKY0** [comment]
If you have the Latest Preview Version, this has been fixed.
