### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by RadGH** [CubeIR/Vanilla-RTX#14]
I'm trying to download through the mcpedl website, but all of the download links just go to another page. Registration through that website doesn't work either - it gives several errors. Is there another way to download this pack without using that awful website?

**Comment by CubeIR** [comment]
Place Vanilla-RTX folder which you can download from here in the following directory:
`C:\Users\%USERNAME%\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\resource_packs`
