### ISSUE TITLE
Lava B/W

### ISSUE THREAD

**Issue by Roeillaun** [CubeIR/Vanilla-RTX#15]
Lava is  B/W  (still and flow) 
testet only in Vanilla-RTX 
![Lava](https://user-images.githubusercontent.com/125166972/218288689-421aead9-b7e0-407a-bcd6-cc932b1605f3.png)

**Comment by CubeIR** [comment]
1. Which Minecraft version are you using?

2. Do you have an stable way of reproducing this issue?

3. If not, does it keep happening all the time?

4. If it does happen all the time, if it possible for you, please send me the world file.

**Comment by Roeillaun** [comment]
1. Bedrock newes update
2. I had until today beacause it was everywhere (every world) since today the lava is its normal coloer again.
3. see point 2
4. I have no Idea wy it workls now.

**Comment by CubeIR** [comment]
Closing this issue. It does not seem to ever happen to anyone else.
