### ISSUE TITLE
Torches now emitting full white light

### ISSUE THREAD

**Issue by paperclipman123** [CubeIR/Vanilla-RTX#16]
I noticed the torches now emit full white light rather than the soft reddish-orange glow after this week's update. Other RTX packs are exhibiting the same behavior so maybe it's a broader issue with the new update?
 
![Screenshot (50)](https://user-images.githubusercontent.com/51208869/218332808-6eb85db0-5d1d-40cc-9f98-f95aea1dbd50.png)

**Comment by CubeIR** [comment]
MCPE-166947 on MC bug tracker.

**Comment by CubeIR** [comment]
Issue was fixed with newer MC versions.
