### ISSUE TITLE
not really an issue more of a feature that would be nice...

### ISSUE THREAD

**Issue by S0me0ne1shere** [CubeIR/Vanilla-RTX#17]
i know we are supposed to send bugs and issue but i wanted to know if its gonna be in your future project to include dynamic lighting, weaving plant and leaves because your pack look incredible just a little more "lively" feature would make this pack the best for sure. well on that false issue. i hope you'll be able to make this pack amazing. BUT for real there this issue that make the water have weird chunks of water and candle emmit no light. thank you for your precious time.

**Comment by CubeIR** [comment]
Vanilla RTX is meant to preserve vanilla Minecraft in every direction, waving plants or similar features that are not available or hinted at in vanilla game are not within its goals.

Bugged chunks of land and water or non-functional candles are issues related to Minecraft itself.
