### ISSUE TITLE
Black dots in the sky during sunset

### ISSUE THREAD

**Issue by Danny1336** [CubeIR/Vanilla-RTX#20]
![Minecraft Screenshot 2023 05 24 - 02 01 27 16](https://github.com/CubeIR/Vanilla-RTX/assets/32264358/eace28bf-5a09-48d8-ac95-e03e9b3d04d9)
--
One more question, is it possible to make the shadows more contrasting?

**Comment by ABUCKY0** [comment]
this is an RTX bug and can't be fixed or changed by an RTX pack
