### ISSUE TITLE
Villagers' hats invisible in current version

### ISSUE THREAD

**Issue by SilentAntenna** [CubeIR/Vanilla-RTX#22]
When using the current texture pack, the accessories worn by villagers are not displayed properly.  
The farmer in the picture below should have a hat:

![image](https://github.com/CubeIR/Vanilla-RTX/assets/19668571/0c9e9f1c-1ffc-4258-94b6-1162983a100c)

**Comment by CubeIR** [comment]
Vanilla RTX does not modify entities.

Known Minecraft RTX issue according to this article:
https://help.minecraft.net/hc/en-us/articles/4408865164173-Minecraft-with-Ray-Tracing-and-Advanced-Graphics-FAQ
