### ISSUE TITLE
Vanilla-PBR

### ISSUE THREAD

**Issue by Uzcoin404** [Cubeir/Vanilla-RTX#23]
does RTX or and graphics card needed to run Vanilla PBR shader? it's not working on Minecraft preview for windows 1.20.30.22

**Comment by Uzcoin404** [comment]
I got this warning when I re-entered game: 
resourcePack.incompatible.graphics.pbr
My DirectX version 12
I have integrated Intel(R) UHD Graphics

**Comment by CubeIR** [comment]
For using Vanilla PBR, you may not need a DirectX hardware ray tracing capable GPU, however a decent GPU is still required.
For integrated graphics, Intel(R) UHD 600 is the minimum requirement.

**Comment by Uzcoin404** [comment]
![image](https://github.com/CubeIR/Vanilla-RTX/assets/82724307/b40479cc-7226-4294-916f-d85ca3cb34ab)
does it support?

**Comment by CubeIR** [comment]
You can use a program such as GPU-Z to see detailed information on your GPU.

**Comment by Uzcoin404** [comment]
My processor: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
