### ISSUE TITLE
Banner designs aren't rendered

### ISSUE THREAD

**Issue by MistakingManx** [CubeIR/Vanilla-RTX#26]
Banner designs simply aren't rendered, version 1.20.0.

Using Luminous Ores and Clear Water.

Without Vanilla RTX:
![image](https://github.com/CubeIR/Vanilla-RTX/assets/28667267/b87ae193-3f21-4931-8630-4a785d13d0f4)

With Vanilla RTX:
![image](https://github.com/CubeIR/Vanilla-RTX/assets/28667267/66a6f0c5-368a-4007-a60d-fa7c23b0612f)

**Comment by CubeIR** [comment]
https://bugs.mojang.com/browse/MCPE-130350

**Comment by MistakingManx** [comment]
What about light blocks (`light_block`)? Since they're completely invisible, I'm not sure you can make it emit light with RTX, but I thought I'd ask anyway. @CubeIR

**Comment by CubeIR** [comment]
> What about light blocks (`light_block`)? Since they're completely invisible, I'm not sure you can make it emit light with RTX, but I thought I'd ask anyway. @CubeIR

Hey, about light blocks, that would require adding custom point lights, which as of now is not possible to add in ray tracing mode, at least not through Vanilla RTX.
There is however a decent chance it might become possible later 🤞
