### ISSUE TITLE
PBR artifacts

### ISSUE THREAD

**Issue by Zekfad** [CubeIR/Vanilla-RTX#27]
Using PBR pack with preview deferred rendering produces artifacts in caves.
It seems like a geometry is not properly connected.

Is it a technical preview current state or pack issue?

<details>
<summary>Deferred rendering</summary>

![image](https://github.com/CubeIR/Vanilla-RTX/assets/8970959/87214007-1040-42cb-9db1-8bb4ca15fe91)

</details>

<details>
<summary>RTX</summary>

![image](https://github.com/CubeIR/Vanilla-RTX/assets/8970959/f9bc1ac3-b5f4-4a47-814a-d96735b5681a)

</details>

**Comment by CubeIR** [comment]
This shouldn't be related to the pack, more likely a Minecraft bug related to chunk culling as you described.
Wat for a deferred technical preview update, you could try to make a bug report about it at https://bugs.mojang.com too (or vote for an existing one) for Mojang to notice this quicker.
