### ISSUE TITLE
Mooshroom mushrooms

### ISSUE THREAD

**Issue by TeddySkrub** [CubeIR/Vanilla-RTX#28]
Mooshroom mushrooms no longer visible with RTX turned on. I know it's probably the same thing as Villager's accessories, but I wonder if it's fixable since on other RTX packs the problem has been solved. It's a shame since this is by far the most tastefully crafted one.
![image](https://github.com/CubeIR/Vanilla-RTX/assets/158606628/8db035fc-5383-4d79-b3e6-a925f7379c70)

**Comment by CubeIR** [comment]
Hi there, it is certainly possible.

Fixing Minecraft's bugs has long been outside of scope of this project's goals, however with the recent 1.20.5 update, I have added an optional experimental subpack within the pack, one of its goals is to slowly address game's many bugs with each update.

Added this issue to the list.

**Comment by TeddySkrub** [comment]
I've been messing around with everything I can find and I've discovered two more bugs. Wither's second phase has an aura around itself, like lightning, it's static black with your pack enabled, also my Trident enchanted with Impaling 5 is black when it sticks into the ground while it's raining.

The experimental features setting adds a problem with the sky, the Sun only spins on one side of the world and never does a full circle around the "globe". Sort of like if you were at the North Pole and the sun only ever barely went under the horzion.

**Comment by CubeIR** [comment]
Wither second phase and Mooshroom issues have been addressed in the upcoming 1.21.20 update for Vanilla RTX. (Experimental option only)
Added the issue with trident to the list, I will attempt to look for a workaround in a future updates.

As for sun path being different in experimental option, that is an intended feature, the reason being default sun path in Minecraft makes the directional light line up of sky with blocks/entire world, it can feel much less dynamic with worse visuals, this drastically improves it.
You can find a list of all intended experimental features on the mcpedl page.

**Comment by CubeIR** [comment]
- Issue with trident doesn't seem fixable through a resource pack.
- Sun path offsets will be less aggressive with a future update.
