### ISSUE TITLE
Frog lights extremely dim with the Vanilla PBR pack enabled.

### ISSUE THREAD

**Issue by pgwipeout** [CubeIR/Vanilla-RTX#34]
On the most recent update, the Vanilla PBR pack makes frog lights extremely dim.
![image](https://github.com/CubeIR/Vanilla-RTX/assets/745725/7f67806e-28f6-4935-8f6b-b4ba1a806310)

Without PBR:
![image](https://github.com/CubeIR/Vanilla-RTX/assets/745725/9563cfe2-2c58-40ac-8f48-a1e2fbe73bce)

**Comment by CubeIR** [comment]
Deferred lighting has changed, next Vanilla PBR update will adapt to the new way things are displayed.
