### ISSUE TITLE
Lightning indoors and outdoors are either too bright or too dark

### ISSUE THREAD

**Issue by outrowed** [CubeIR/Vanilla-RTX#35]
I was playing a minigame on the Hive server, and I noticed some thing particularly jarring about the lightnings when walking around small closed spaces. When I'm staying indoors, the lightning outdoors are too bright, and when I'm staying outdoors, the lightning indoors are too dark. This usually happens when I'm on small closed corners, houses, corridors - you get it.

I suspect this is because of a heavy amount of HDR being used here behind the scenes, making it too over-saturated (but this is just purely a speculation, I'm not in any way a professional in computer graphics 👀.)

Take a look at these screenshots:

**Staying indoors, the outdoors are too bright**
![cave looking outside](https://github.com/CubeIR/Vanilla-RTX/assets/59441185/98c71793-ac00-4968-928f-3f552db887ec)
![small-corners looking outside](https://github.com/CubeIR/Vanilla-RTX/assets/59441185/6f184eb1-3d80-4e82-b4f9-0ff4ad5e08dc)

**Staying outdoors, the indoors are too dark**
![small-corners looking inside](https://github.com/CubeIR/Vanilla-RTX/assets/59441185/787e2ae9-bec9-4f29-a68e-15a6c3a42cc4)
![cave looking inside](https://github.com/CubeIR/Vanilla-RTX/assets/59441185/3f6fcdd3-6a7a-4bb7-9707-d1f91936c0ae)

**Dramatic lightning changes, outdoor vs. indoor**
![cave outdoor](https://github.com/CubeIR/Vanilla-RTX/assets/59441185/3583b80c-1958-4fc5-8c23-b0439e3c0c8f)
![cave indoor](https://github.com/CubeIR/Vanilla-RTX/assets/59441185/d57900e6-011b-479f-9dd0-94ab5205dece)

**Video**

https://github.com/CubeIR/Vanilla-RTX/assets/59441185/2bd473cd-833d-475f-a72c-547fa3c64484

Tested on Minecraft v1.20.81, using Vanilla PBR v1.3.0

**Comment by CubeIR** [comment]
It's auto-exposure! it is necessary to balance out the lighting in a lot of games.
Later versions should look a bit different, give it a try you might find it less odd. 🙂
In the end this isn't really an issue, so I'm closing it.
