### ISSUE TITLE
No name nor description filled in. Why?

### ISSUE THREAD

**Issue by NicholasFlamy** [Cubeir/Vanilla-RTX#38]
https://github.com/Cubeir/Vanilla-RTX/blob/0994eeee916dfb199e7a2570302909a09fb3fa2a/Vanilla-RTX/manifest.json#L5

**Comment by NicholasFlamy** [comment]
Also, if you import it into Minecraft the folder for the resource pack is named "pack.name"

**Comment by Karpatok9089** [comment]
I think its for multi-language support.
The `pack.name` is supposed to get replaced with Vanilla RTX in game.

**Comment by NicholasFlamy** [comment]
> I think its for multi-language support. The `pack.name` is supposed to get replaced with Vanilla RTX in game.

Interesting, that seems to make sense, but it's strange that the folder is named `pack.name`. I don't think it matters but maybe I should submit that to the Minecraft bug tracker since it is a little annoying when looking in the resource pack folder.
