### ISSUE TITLE
Shader issue

### ISSUE THREAD

**Issue by Nasrawi94** [Cubeir/Vanilla-RTX#39]
Which folder I should paste the shader file in it on android

**Comment by Cubeir** [comment]
I'm not sure about exact folder paths on Android, but if you turn each individual folder into a .zip, then rename the zip file extension to .mcpack, you will be able to automatically import it to your Minecraft installation by trying to open the mcpack file through Minecraft.

Use Minecraft Preview for Vanilla PBR.
