### ISSUE TITLE
Horse texture bugs out

### ISSUE THREAD

**Issue by WannaBeDev64** [CubeIR/Vanilla-RTX#5]
Minecraft ver. 1.19.0
Various horse textures turn pitch black when the pack is enabled.
![Screenshot 2022-06-08 153307](https://user-images.githubusercontent.com/62036967/172702373-19507e96-b15a-45cc-b074-0c6a13bc0488.png)
w/o pack
![Screenshot 2022-06-08 153534](https://user-images.githubusercontent.com/62036967/172702403-ae7d6766-74f5-4b88-a93a-b4cc3fcc3050.png)
same entities with pack

**Comment by Zekhaze** [comment]
same with warden 
![image](https://user-images.githubusercontent.com/71511976/172727476-3183cc4d-208b-472d-827a-a233abe0e776.png)

**Comment by CubeIR** [comment]
Game bug. https://bugs.mojang.com/browse/MCPE-132747
