### ISSUE TITLE
Black glitch

### ISSUE THREAD

**Issue by RainyArcher** [CubeIR/Vanilla-RTX#7]
v.1.19.10, RTX 3060, no mods, no resource packs, original launcher, latest planet minecraft version of Vanilla RTX
Every skin and some 3D models turn black, works in both singleplayer and multiplayer. Its not a variation of a pink glitch, I tried reloading resource packs and restrating Minecraft. 
![Screenshot (418)](https://user-images.githubusercontent.com/74546799/178678608-568c570d-2589-4eff-8e82-36f01df81778.png)
![Screenshot (419)](https://user-images.githubusercontent.com/74546799/178678625-6b26c361-523c-44a8-8f4f-3ae5100cfc42.png)

**Comment by spacewaretwo** [comment]
as well

**Comment by RuiRayZ** [comment]
me too

**Comment by Pigeon2333** [comment]
Me too

**Comment by unlocko** [comment]
I am also having this issue

**Comment by RainyArcher** [comment]
Glitch was fixed by Mojang. Now its still the best rtx pack
