### ISSUE TITLE
Candles do not provide lighting

### ISSUE THREAD

**Issue by qPexLegendary** [CubeIR/Vanilla-RTX#9]
If you light a candle, there will be no lighting.

**Comment by qPexLegendary** [comment]
![image](https://user-images.githubusercontent.com/54776640/196861349-c3e64f1a-6f8e-48ef-a24e-a9aa269b4ec1.png)

**Comment by CubeIR** [comment]
https://bugs.mojang.com/browse/MCPE-132021
